feat: add lightbox for case-study
masterpointio/masterpoint.io pull request #35
Opened 2024-10-31 23:29 UTC by Gowiem

2024-11-01 18:12 UTC, Gowiem commented on content/landing/power-digital-case-study.md
> +<a href="/download/power-digital-case-study.pdf" class="button">Download Our PDF Case Study &rsaquo;</a>
We don't want to do this. Please don't suggest this in the future.

2024-11-04 15:47 UTC, oycyc requested changes

2024-11-04 15:47 UTC, oycyc commented on content/landing/power-digital-case-study.md
> +> The result was a **10x reduction** in infrastructure automation costs, **significantly faster** plan and apply cycles, and a **more resilient**, scalable infrastructure that can easily onboard new
Did someone say this or is this just a summary?

2024-11-04 15:47 UTC, oycyc commented on content/landing/power-digital-case-study.md
> +> The result was a **10x reduction** in infrastructure automation costs, **significantly faster** plan and apply cycles, and a **more resilient**, scalable infrastructure that can easily onboard new
```suggestion
> The result was a **10x reduction** in infrastructure automation costs, **significantly faster** plan and apply cycles, and a **more resilient**, scalable infrastructure that can easily onboard new clients.
```

2024-11-04 15:47 UTC, oycyc commented on content/landing/power-digital-case-study.md
> +> The result was a **10x reduction** in infrastructure automation costs, **significantly faster** plan and apply cycles, and a **more resilient**, scalable infrastructure that can easily onboard new
Nevermind, I thought it was intended to be like a quote.

2024-11-07 15:27 UTC, oycyc approved these changes

2024-11-07 15:27 UTC, merged